version: '2'

services:
# Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  # Start transformation worker
  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform

  # Start OCR worker
  openocrworker:
    image: tleyden5iwx/${OPEN_OCR_INSTANCE}
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/

  # Start http server
  openocr:
    image: tleyden5iwx/${OPEN_OCR_INSTANCE}
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292
